name = "spiff-tracker"
compatibility_date = "2026-04-17"
pages_build_output_dir = "./public"

[[d1_databases]]
binding = "DB"
database_name = "spiff-tracker"
database_id = "bd10b325-a027-48da-91c1-34f411c4d1ab"

[triggers]
crons = [
  "0 9 1 6 *",
  "0 9 6 6 *",
  "0 9 1 7 *",
  "0 9 6 7 *",
  "0 14 * * 1"
]
